### ISSUE TITLE
yarn bootstrap has issues 

### ISSUE THREAD

**Issue by byteblock-labs** [tqtezos/minter#425]
Runs into this issue:
Bootstrapping contracts...
Encountered error:
[2021-05-12T10:51:37.576] [ERROR] [default] - Error while bootstrapping environment custom
(node:2208) UnhandledPromiseRejectionWarning: undefined
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2208) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2208) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
Encountered error:
[2021-05-12T10:51:37.576] [ERROR] [default] - Error: Unsupported key type
    at new InMemorySigner (/tmp/minter/node_modules/@taquito/signer/src/taquito-signer.ts:85:15)
    at Function.<anonymous> (/tmp/minter/node_modules/@taquito/signer/src/taquito-signer.ts:39:12)
    at step (/tmp/minter/node_modules/@taquito/signer/dist/taquito-signer.umd.js:61:27)
    at Object.next (/tmp/minter/node_modules/@taquito/signer/dist/taquito-signer.umd.js:42:57)
    at fulfilled (/tmp/minter/node_modules/@taquito/signer/dist/taquito-signer.umd.js:32:62)
Encountered error:
error Command failed with exit code 1.
Encountered error:
error Command failed with exit code 1.

how to solve it?

**Comment by obstropolos** [comment]
Hey @byteblock-labs - what version of OpenMinter are you currently using?

**Comment by mycodecrafting** [comment]
Hey @byteblock-labs the error here is `Unsupported key type`.  When the input wizard asks you for your secret/private key, can you let me know the first 4 characters of the key? Please do not post the entire key ;-)

**Comment by byteblock-labs** [comment]
We solved that issue. the promise was not cathed properly. Do you want me to submit the patch?

**Comment by sebuhbitcoin** [comment]
I ran into the same issue just now. 

Would love to try again. What's the way to fix it?

**Comment by sebuhbitcoin** [comment]
my issue is it crashes right after inputting the private key of the contract originator address,

**Comment by obstropolos** [comment]
> We solved that issue. the promise was not cathed properly. Do you want me to submit the patch?
@byteblock-labs - sure feel free to open a pull request. Thank you.

**Comment by byteblock-labs** [comment]
Are u still looking for the solution?

**Comment by WizardsKnow** [comment]
@byteblock-labs what format is expected for the secret key?
